# Plugins
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

# Conversion
# markdown: redcarpet
# highlighter: pygments
excerpt_separator: ""

# Outputting
permalink: "/:title"
paginate_path: "/pagina-:num"
paginate: 10
timezone: America/Sao_Paulo

# Markdown Processors
kramdown:
  input: GFM

# Site settings
title: "Warley"
description: Artigos e tutoriais sobre desenvolvimento WEB
logo: https://lh3.googleusercontent.com/a-/AOh14Gi9a61q-Zonw0_B4AsHcKN4aK_hzlnHDq5b7gFsHpw=s96-c-rg-br100
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
url: "https://warleyerocha.github.io"

# Default author
author:
  name: Warley Rocha
  image: https://lh3.googleusercontent.com/a-/AOh14Gi9a61q-Zonw0_B4AsHcKN4aK_hzlnHDq5b7gFsHpw=s96-c-rg-br100

# social icons and sharing options
social:
  - icon: github
    url:  https://github.com/warleyerocha
    desc: Fork me on github
    share_url:
    share_title:
    share_link:
